import { GeistProvider, myTheme } from "@/components/Geist";

import "./global.css";
import "./geist.gen.css";
import { Crisp } from "@/components/Crisp";

export const metadata = {
	title: "Reacher Email Verification",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html>
			<body>
				<GeistProvider themes={[myTheme]} themeType="default">
					{children}
				</GeistProvider>
				<Crisp />
			</body>
		</html>
	);
}
