import { CssBaseline, GeistProvider, myTheme } from "@/components/Geist";

import "./global.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<GeistProvider themes={[myTheme]} themeType="default">
					<CssBaseline />
					{children}
				</GeistProvider>
			</body>
		</html>
	);
}
