-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: is_reachable_type

-- DROP TYPE IF EXISTS public.is_reachable_type;

CREATE TYPE public.is_reachable_type AS ENUM
    ('safe', 'invalid', 'risky', 'unknown');

ALTER TYPE public.is_reachable_type
    OWNER TO postgres;

ALTER TABLE IF EXISTS public.calls
    ADD COLUMN backend text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.calls
    ADD COLUMN backend_ip text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.calls
    ADD COLUMN duration integer;

ALTER TABLE IF EXISTS public.calls
    ADD COLUMN is_reachable is_reachable_type;
