name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18
            - run: yarn install
            - run: yarn lint
